Weather v1.0
misselliev/dulce-raindrops pull request #1
Opened 2019-11-05 04:54 UTC by misselliev

2019-11-06 02:49 UTC, AdnanAfsari commented on src/index.js
> +    async function getWeather(city) {
use Arrow function

2019-11-06 02:56 UTC, AdnanAfsari requested changes
**Status: Changes Required**

Hello @misselliev ✋ 

Nice work but some small changes to get approval.

- [x] usage of arrow functions instead of the function keyword.

- [x] The application should make different requests for the Celsius data and the Fahrenheit data. Instead of using math to convert it to the other unit.

Please make those changes and submit for another review.

Happy Coding
Adnan Afsari

2019-11-06 02:56 UTC, AdnanAfsari commented on src/index.js
> +function loadData(data) {
use Arrow function

2019-11-06 05:26 UTC, misselliev commented
Hi @AdnanAfsari thank you for your comments! Just a question on the temperature unit topic, if we already have the temperature data why do we need to do another request and fetch it again instead of the toggle on click?

2019-11-07 03:16 UTC, AdnanAfsari commented
**Status: Approved**

Hello @misselliev ✋ 

The purpose of this project is to learn making network request.The more you practice the better you get.
if you check the project requirement you will find it there, Look at the screenshot below i taken from there.
<img width="838" alt="Screenshot 2019-11-07 at 9 10 06 AM" src="https://user-images.githubusercontent.com/8613710/68357144-97869080-013e-11ea-941f-8b0246d6a73d.png">

Anyway As you have done everything right, I am approving this project at this moment but i want you work on this requirement and fulfill it 😄 .

Happy Coding
Adnan Afsari

2019-11-07 04:07 UTC, merged